Rodzaje ruchu:\
Swap - losujemy dwa miasta i zamieniamy je ze sobą.\
Insercja - losujemy miasto i punkt w którym je umieszczamy.\
Zamiana kolejności - losujemy dwa punkty i między nimi zamieniamy kolejność.\
\
Sąsiedztwo to dwa przypadki które różnią się między sobą jednym ruchem\
\
Klasyczny algorytm wspinaczki z multistartem: po każdym ruchu liczymy drogę i sprawdzamy czy jest mniejsza czy nie, wybieramy tylko lepsze opcje. Multistart polega na wielokrotnym odpaleniu algorytmu z losowaniem punktu startowego.\
\
Algorytm symulowanego wyżarzania: zmodyfikowany algorytm wspinaczki, jeśli znalezione rozwiązanie jest gorsze to nadal je rozważamy, na podstawie tego jak bardzo jest gorsze oraz od temperatury.\
Temperatura jest wysoka na początku działania algorytmu i spada razem z czasem wykonywania algorytmu, im niższa temperatura tym mniejsze prawdopodobieństwo wybrania gorszego rozwiązania, bo algorytm już trochę działa i zakładamy że jest w lepszym miejscu niż na początku.\
Pozwala on nam wyjść z niektórych ekstremów lokalnych dzięki możliwości przyjęcia gorszego rozwiązania.\
\
Tabu search:\
Sąsiedztwo wygląda tutaj inaczej: przy swapie losujemy jedną liczbę i zamieniamy wszystkie kombinacje z tą liczbą, ze wszystkich kombinacji wybieramy najlepszą.\
Następnie taka kombinacja trafia na listę tabu, czyli takiej samej zamiany nie można wykonać przez określoną kolejną liczbę ruchów.\
\
Funkcja aspiracji to funkcja, która pod pewnymi warunkami pozwala wykonać ruch z listy tabu ale nie trzeba tego implementować.\
\
Odpowiednia długość listy tabu pozwala wyjść z niektórych ekstremów lokalnych, jeśli będzie za krótka to możemy nie wyjść z ekstremum lokalnego, jeśli będzie za długa to możemy wyjść z ekstremum niepotrzebnie.


In [25]:
import numpy as np
import pandas as pd
import math
import random

In [26]:
#wspinaczka z multistartem
distance = np.array([[0,2,4,1,5],
                    [2,0,3,8,7],
                    [4,3,0,5,1],
                    [1,8,5,0,3],
                    [5,7,1,3,0]])

In [27]:
def Odleglosc(distance, trasa):
    suma = 0
    n = len(trasa)
    
    for i, current_city in enumerate(trasa):
        next_city = trasa[(i + 1) % n]  # Use modulo to handle the last element
        suma += distance[current_city][next_city]

    return suma

In [28]:
#swap
def Swap(trasa):
    trasa_temp = trasa.copy()
    #print(trasa)
    swap = np.random.choice(trasa_temp,2,replace=False)
    temp = trasa_temp[swap[0]]
    trasa_temp[swap[0]] = trasa_temp[swap[1]]
    trasa_temp[swap[1]] = temp
    #print(swap)
    #print(trasa)
    return trasa_temp

#insercja
def Insercja(trasa):
    trasa_temp = trasa.copy()
    insercja = np.random.choice(trasa_temp,2,replace=False)
    #print(trasa_temp)
    #print(insercja)
    temp = trasa_temp[insercja[0]]
    trasa_temp = np.delete(trasa_temp,insercja[0])
    trasa_temp = np.insert(trasa_temp,insercja[1],temp)
    #print(trasa_temp)
    return trasa_temp

def Zamiana(trasa):
    trasa_temp = trasa.copy()
    zamiana = np.random.choice(trasa_temp,2,replace=False)
    zamiana.sort()
    #print(trasa_temp)
    #print(zamiana)
    for i in range(math.ceil((zamiana[1]-zamiana[0])/2)):
        temp = trasa_temp[zamiana[1]]
        trasa_temp[zamiana[1]] = trasa_temp[zamiana[0]]
        trasa_temp[zamiana[0]] = temp
        zamiana[1] -= 1
        zamiana[0] += 1
    #print(trasa_temp)
    return trasa_temp

In [29]:
#Zamiana(trasa)

In [30]:
#trasa = np.arange(len(distance))
#np.random.shuffle(trasa)
#Insercja(trasa)

In [31]:
#temp = trasa[0] #temp = 4
#trasa = np.delete(trasa,0)
#trasa = np.insert(trasa,4,3)

In [32]:
#ruch polegający na swapie, sprawdzenie sąsiadów, zwrot mniejszej trasy
def Ruch_swap(distance,trasa):
    odl = Odleglosc(distance,trasa)
    trasa_new = Swap(trasa)
    odl_new = Odleglosc(distance,trasa_new)
    if odl_new < odl:
        return trasa_new, odl_new
    return trasa, odl, trasa_new, odl_new

#ruch polegający na insercji, sprawdzenie sąsiadów, zwrot mniejszej trasy
def Ruch_insercja(distance,trasa):
    odl = Odleglosc(distance,trasa)
    trasa_new = Insercja(trasa)
    odl_new = Odleglosc(distance,trasa_new)
    if odl_new < odl:
        return trasa_new, odl_new
    return trasa, odl

#ruch polegający na zamianie, sprawdzenie sąsiadów, zwrot mniejszej trasy
def Ruch_zamiana(distance,trasa):
    odl = Odleglosc(distance,trasa)
    trasa_new = Zamiana(trasa)
    odl_new = Odleglosc(distance,trasa_new)
    if odl_new < odl:
        return trasa_new, odl_new  
    return trasa, odl

In [33]:
distance = pd.read_excel("Dane_TSP_48.xlsx")
distance = distance.to_numpy()
distance = np.delete(distance,0,1)
distance

array([[   0, 1495,  381, ...,  488,  753, 1184],
       [1495,    0, 1135, ..., 1727, 1388,  661],
       [ 381, 1135,    0, ...,  640,  591,  810],
       ...,
       [ 488, 1727,  640, ...,    0,  520, 1242],
       [ 753, 1388,  591, ...,  520,    0,  801],
       [1184,  661,  810, ..., 1242,  801,    0]], dtype=int64)

In [34]:
def IHC(distance, ruch, n_iter_ruch, n_iter):  # ruch = {Swap, Insercja, Zamiana}
    min_iter = []
    for i in range(n_iter):
        trasa = np.arange(len(distance))
        np.random.shuffle(trasa)
        odl = Odleglosc(distance,trasa)
        for j in range(n_iter_ruch):
                trasa_new = ruch(trasa)
                odl_new = Odleglosc(distance,trasa_new)
                if odl_new < odl:
                    odl = odl_new
                    trasa = trasa_new
        min_iter.append((i,trasa,odl))
    return min_iter
wynik = IHC(distance,Swap,1000,100)
wynik.sort(key=lambda x: x[2])
wynik[0:10]



[(55,
  array([23,  9,  3, 25, 34, 44, 31, 21, 15, 40, 28,  1, 41,  4, 47, 10, 11,
         27, 26, 18, 42, 16, 36, 45, 14, 39, 13, 12, 24, 38, 20, 46, 32, 19,
         30, 43, 17,  6,  5, 29, 35, 37,  8,  0,  7,  2, 22, 33]),
  16516),
 (9,
  array([42, 20, 31, 38, 24, 13, 23, 47, 41,  9, 34, 44,  3, 25,  4, 22, 12,
         10, 21,  2, 15,  7, 37, 30, 14, 32, 39,  0, 40, 28,  1, 33, 46, 19,
         11,  8, 45, 17, 29, 26, 18, 36,  5, 27,  6, 43, 35, 16]),
  16844),
 (23,
  array([35, 36, 16, 42, 29,  6, 17, 30, 43, 45, 32, 31, 12, 38, 34, 44,  3,
          1, 28, 33,  4, 23,  9, 25, 41, 47, 24, 13, 22, 20, 46, 19, 11, 18,
         26,  5, 27, 37,  8,  7, 15, 40, 21,  2, 10,  0, 39, 14]),
  16898),
 (87,
  array([43, 30, 40, 28,  1,  4, 38, 31, 44, 34,  3, 25, 10, 39, 11, 14, 45,
         37,  8, 19, 46, 20, 12, 24,  9, 23, 41, 47, 33, 21,  7, 15,  0,  2,
         13, 22, 32, 35,  5, 36, 18, 16, 26, 42, 29, 27, 17,  6]),
  16917),
 (98,
  array([43, 30, 37,  6,  7,  0,  1, 28,  4, 41

In [35]:
def Geometric(T,alpha):
    return alpha*T

def Slow(T,alpha):
    return T/(1+alpha*T)


In [145]:
def SA(distance, ruch, n_iter_ruch, n_iter, T_start, cooling, alpha):  # ruch = {Swap, Insercja, Zamiana}, cooling = {Geometric, Slow}, alpha = cooling param 
    min_iter = []
    for i in range(n_iter):
        T = T_start
        trasa = np.arange(len(distance))
        np.random.shuffle(trasa)
        odl = Odleglosc(distance,trasa)
        for j in range(n_iter_ruch):
                trasa_new = ruch(trasa)
                odl_new = Odleglosc(distance,trasa_new)
                diff_odl = odl_new - odl
                if diff_odl < 0:
                    odl = odl_new
                    trasa = trasa_new
                elif random.random() < math.exp(-diff_odl/T):
                    odl = odl_new
                    trasa = trasa_new
                T = cooling(T,alpha)
        min_iter.append((i,trasa,odl))
    return min_iter
wynik = SA(distance,Swap,1000,100,100,Slow,0.1)
wynik.sort(key=lambda x: x[2])
wynik[0:10]

[(57,
  array([27, 35,  6, 17, 43, 46, 20, 12, 13, 24, 38, 31, 32, 30, 45, 14, 11,
         19, 22,  2, 33, 39,  0,  8, 37,  7, 21, 15, 40,  4, 23,  9,  3, 44,
         34, 25, 47, 41,  1, 28, 10, 29, 36, 18, 16, 42, 26,  5]),
  15937),
 (4,
  array([ 6, 36, 26, 42, 20, 38, 31, 24, 13,  4, 47, 41,  3, 25,  1, 28, 40,
         33,  2, 15, 21, 22, 44, 34,  9, 23, 46, 12, 10,  7,  0,  8, 11, 14,
         39, 45, 35, 17, 43, 30, 27,  5, 29, 18, 16, 19, 32, 37]),
  16823),
 (91,
  array([ 5, 27, 29, 36, 26, 16, 42, 14, 17, 43, 37, 19, 11, 22,  2, 15, 21,
          1, 25,  3, 41, 31, 38, 24, 46, 20, 44, 34,  9, 23, 47,  4, 28, 33,
         40, 39,  0,  8,  7, 13, 12, 10, 32, 45, 30, 35,  6, 18]),
  16865),
 (39,
  array([42,  5, 27,  6, 43, 45, 32, 19, 46, 20, 12, 10, 13, 24, 47, 41,  4,
         33, 37, 30, 14, 34, 44,  3, 25, 38, 31, 23,  9,  1, 28, 15,  0,  7,
          8, 39, 21,  2, 40, 22, 11, 17, 35, 29, 36, 18, 26, 16]),
  16899),
 (40,
  array([ 0,  2, 33, 13, 24, 32, 29, 18, 26, 36

In [143]:
# wersja SA gdzie warunkiem stopu jest temperatura a nie liczba iteracji 
# (chyba lepiej tak bo upewniamy sie ze temperatura jest niska a podajac liczbe iteracji mozemy skonczyc na wysokiej temperaturze)
# mozna tez dodac warunek stopu ze po np 100 iteracjach bez poprawy rozwiazania to koniec

def SA(distance, ruch, n_iter, T_start, T_stop, cooling, alpha):  # ruch = {Swap, Insercja, Zamiana}, cooling = {Geometric, Slow}, alpha = cooling param 
    min_iter = []
    for i in range(n_iter):
        T = T_start
        trasa = np.arange(len(distance))
        np.random.shuffle(trasa)
        odl = Odleglosc(distance,trasa)
        while(T > T_stop):
                trasa_new = ruch(trasa)
                odl_new = Odleglosc(distance,trasa_new)
                diff_odl = odl_new - odl
                if diff_odl < 0:
                    odl = odl_new
                    trasa = trasa_new
                elif random.random() < math.exp(-diff_odl/T):
                    odl = odl_new
                    trasa = trasa_new
                T = cooling(T,alpha)
        min_iter.append((i,trasa,odl))
    return min_iter
wynik = SA(distance,Swap,100,100,0.01,Slow,0.1)
wynik.sort(key=lambda x: x[2])
wynik[0:10]

[(25,
  array([31, 24, 12, 10, 22, 39, 14, 11, 17, 36, 18, 26, 16, 42, 29,  5, 27,
         19, 46, 32, 45, 30, 37, 13, 47,  4, 28,  1, 23, 44, 34,  9,  3, 25,
         41, 40, 33,  2, 21, 15,  7,  0,  8, 43,  6, 35, 20, 38]),
  14977),
 (18,
  array([40, 14, 35,  6, 17, 43, 32, 45, 11, 19, 29, 42, 16, 26, 18, 36,  5,
         27, 30,  8, 39,  2, 33, 28,  1, 41,  9, 23, 25,  3, 34, 44, 31, 38,
         20, 24,  4, 47, 13, 12, 46,  0,  7, 37, 10, 22, 21, 15]),
  15106),
 (65,
  array([28,  1,  3, 34, 44,  9, 38, 31, 20, 19, 29, 42, 16, 18, 26, 36, 45,
          8, 39,  2, 22, 13, 10, 14, 32, 46, 11, 30, 37, 21, 33, 40, 15,  0,
          7, 35, 27,  5,  6, 17, 43, 12, 24, 47, 23, 25, 41,  4]),
  16468),
 (71,
  array([12, 10, 11, 32, 45, 29, 26, 16, 42, 19, 13, 47, 23, 41,  9, 44, 34,
          3, 25, 28,  1,  4, 24, 22,  0, 21, 15,  2, 33, 40, 31, 38, 35, 37,
         30, 17, 27, 36, 18,  5,  6, 43,  8,  7, 39, 14, 46, 20]),
  16505),
 (69,
  array([24, 21, 13, 22,  4, 47, 41,  9, 23, 3

In [38]:
# funkcje pomocnicze do sprawdzenia ile iteracji odpowiada parametrowi T_stop
def T_stopToIter(T_start, T_stop, cooling, alpha):
    T = T_start
    i = 0
    while(T > T_stop):
        T = cooling(T,alpha)
        i += 1
    return i
def IterToT_stop(T_start, n_iter, cooling, alpha):
    T = T_start
    for i in range(n_iter):
        T = cooling(T,alpha)
    return T
print(T_stopToIter(100,0.01,Slow,0.1))
IterToT_stop(100,100,Slow,0.1)

1000


0.09990009990009993

In [142]:
# #algorytm ze swapem
# trasa = np.arange(len(distance))
# np.random.shuffle(trasa)
# licza_iteracji = 5

# print("Start")
# print(trasa)
# print(Odleglosc(distance,trasa))
# for i in range(licza_iteracji):
#     print("\n{} iteracja".format(i+1))
#     trasa = Ruch_swap(distance,trasa)
#     print(trasa)
#     print(Odleglosc(distance,trasa))


In [141]:
# #algorytm z insercją
# trasa = np.arange(len(distance))
# np.random.shuffle(trasa)
# licza_iteracji = 5

# print("Start")
# print(trasa)
# print(Odleglosc(distance,trasa))
# for i in range(licza_iteracji):
#     print("\n{} iteracja".format(i+1))
#     trasa = Ruch_insercja(distance,trasa)
#     print(trasa)
#     print(Odleglosc(distance,trasa))

In [140]:
# #algorytm z zamianą
# trasa = np.arange(len(distance))
# np.random.shuffle(trasa)
# licza_iteracji = 1000

# print("Start")
# print(trasa)
# print(Odleglosc(distance,trasa))
# for i in range(licza_iteracji):
#     print("\n{} iteracja".format(i+1))
#     trasa = Ruch_zamiana(distance,trasa)
#     print(trasa)
#     print(Odleglosc(distance,trasa))

In [137]:
#NN
min_odl = []
for n in range(100):
    potencjalne = np.arange(len(distance))
    trasa = np.zeros(len(distance),dtype=int)
    trasa[0] = np.random.choice(potencjalne,1)
    potencjalne = np.delete(potencjalne,int(trasa[0]))

    for cur in range(1,len(trasa)):
        odleglosci = []
        for i in range(len(potencjalne)):
            trasa[cur] = potencjalne[i]
            odleglosci.append((potencjalne[i],Odleglosc(distance,trasa[0:cur+1])))
        odleglosci.sort(key=lambda x: x[1])
        trasa[cur] = odleglosci[0][0]
        potencjalne = np.delete(potencjalne,potencjalne==trasa[cur])
    min_odl.append((Odleglosc(distance,trasa),trasa))
    
min_odl.sort(key=lambda x:x[0])
min_odl[:10]

[(13251,
  array([ 8,  0,  7, 37, 30, 45, 14, 39, 11, 32, 43, 17,  6, 35, 27,  5, 29,
         36, 18, 26, 42, 16, 19, 10, 22,  2, 21, 15, 40, 33, 13, 12, 46, 20,
         24, 38, 31, 47,  4, 28,  1, 41, 23,  9, 25,  3, 34, 44])),
 (13251,
  array([ 8,  0,  7, 37, 30, 45, 14, 39, 11, 32, 43, 17,  6, 35, 27,  5, 29,
         36, 18, 26, 42, 16, 19, 10, 22,  2, 21, 15, 40, 33, 13, 12, 46, 20,
         24, 38, 31, 47,  4, 28,  1, 41, 23,  9, 25,  3, 34, 44])),
 (13251,
  array([ 8,  0,  7, 37, 30, 45, 14, 39, 11, 32, 43, 17,  6, 35, 27,  5, 29,
         36, 18, 26, 42, 16, 19, 10, 22,  2, 21, 15, 40, 33, 13, 12, 46, 20,
         24, 38, 31, 47,  4, 28,  1, 41, 23,  9, 25,  3, 34, 44])),
 (13414,
  array([44, 34,  9, 23, 41, 25,  3,  1, 28,  4, 47, 38, 31, 24, 13, 12, 20,
         46, 10, 22, 33,  2, 21, 15, 40, 39, 11, 19, 32, 14, 45,  8,  0,  7,
         37, 30, 43, 17, 35,  6, 27, 29, 42, 26,  5, 36, 18, 16])),
 (13414,
  array([44, 34,  9, 23, 41, 25,  3,  1, 28,  4, 47, 38, 31, 24, 13